version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - networkName

  # command-api can be scaled independently
  command-api:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - redis
    entrypoint: "./bbb command-api"
    networks:
      - networkName

  # query-api can be scaled independently
  query-api:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - redis
    entrypoint: "./bbb query-api"
    networks:
      - networkName

networks:
  networkName:
    driver: bridge
